--- kernel/samsung/msm8660-common/Makefile	2013-08-27 20:38:59.880914055 -0600
+++ patches/kernel/samsung/msm8660-common/Makefile	2013-08-26 03:50:56.920922463 -0600
@@ -193,7 +193,7 @@
 # Note: Some architectures assign CROSS_COMPILE in their arch/*/Makefile
 export KBUILD_BUILDHOST := $(SUBARCH)
 ARCH		?= arm
-CROSS_COMPILE	?= /opt/toolchains/arm-eabi-4.4.3/bin/arm-eabi-
+CROSS_COMPILE	?= ${WORKING_DIR}/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-
 
 # Architecture as present in compile.h
 UTS_MACHINE 	:= $(ARCH)
